apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testnet-headlamp-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/ten-protocol/ten-apps.git
    targetRevision: main
    path: nonprod-argocd-config/apps/envs/testnet/manifests/headlamp
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
