apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "ten-tools.fullname" . }}-faucet
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.faucet.host }}`)
      kind: Rule
      services:
        - name: {{ include "ten-tools.fullname" . }}-faucet
          port: 80
