apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "ten-tools.fullname" . }}-tenscan-fe
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.tenscan.fe.host }}`){{- if .Values.tenscan.fe.host2 }} || Host(`{{ .Values.tenscan.fe.host2 }}`){{- end }}
      kind: Rule
      services:
        - name: {{ include "ten-tools.fullname" . }}-tenscan-fe
          port: 80
  tls:
    certResolver: le