apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-repo/ten-protocol-argo.git
    targetRevision: HEAD
    path: external-secrets/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true