apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ten-protocol/ten-apps.git
    targetRevision: HEAD
    path: external-secrets/dev
    directory:
      recurse: true
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true