apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-sequencer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ten-protocol/ten-apps.git
    targetRevision: main
    path: charts/ten-node             # <-- Path to actual chart
    helm:
      valueFiles:
        - values-dev-sequencer.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
