apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ten-tools
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ten-protocol/ten-apps.git
    targetRevision: main
    path: charts/ten-tools             # <-- Path to actual chart
    helm:
      valueFiles:
        - ../../nonprod-argocd-config/apps/envs/dev/valuesFile/values-dev-tools.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy: 
    syncOptions:
      - CreateNamespace=true
