
enclave:
    image:
        repository: testnetobscuronet.azurecr.io/obscuronet/uat_enclave
        tag: "latest"
    nodeSelector:
        kubernetes.io/hostname: aks-sgxpool-23084093-vmss000000

    secretEnv:
        ENCLAVE_DB_SQLITEPATH: ""

host:
    image:
        repository: "testnetobscuronet.azurecr.io/obscuronet/uat_host"
        tag: "latest"
    fqdn: uat-testnet-sequencer.ten.xyz
edb:    
    nodeSelector:
        kubernetes.io/hostname: aks-sgxpool-23084093-vmss000000
config:
    network:
        chainid: 443
        genesisjson: '{}'
        batch:
            interval: 1s
            maxinterval: 1s
            maxsize: 56320
        gas:
            basefee: "1000000000"
            mingasprice: "1000000000"
            paymentaddress: "0xd6C9230053f45F873Cb66D8A02439380a37A4fbF"
            batchexecutionlimit: "30000000"
            localexecutioncap: "300000000000"
        l1:
            chainid: "11155111"
            blocktime: 15s
            starthash: "0x3100c7d0cb4d7777b930b3709779833a3c71ccdc89dedc7b6560cf402f43df95"
            l1contracts:
                messagebus: "0x7C948e8eDdCe94CCd11068A92B1A97bb61F1A65a"
                bridge: "0x0C084797164F4347AEa1e2c9cD29FdC710FBd63F"
                crosschain: "0x1713E26c9251eEDBF9D09dF692d2682F050Fe926"
                rollup: "0x653Aa03F4b6d3f187d550113dEaC51Ccaa8DE477"
                enclaveRegistry: "0x6Ac08597CfE1D567776e8831E4ec3D5c77320017"
                networkConfig: "0xa63592Db46df35C4Ce0dFF98d45d8CDE010B09f0"
        rollup:
            interval: 15m0s
            maxinterval: 10m0s
            maxsize: 131072
        sequencer:
            p2paddress: uat-testnet-sequencer.ten.xyz:10000
            systemcontractsupgrader: "0x11431A88Fc53F3eE5Ae263067F96EAF91A0f0974"
        crosschain:
            interval: 6s
    node:
        nodetype: "sequencer"
        name: "obscuronode"
        isgenesis: true
    host:
        db:
            useinmemory: false
            sqlitepath: ""
        debug:
            enablemetrics: true
            metricshttpport: 0
            enableprofiler: false
            enabledebugnamespace: true
        enclave:
            rpcaddresses:
                - obscuronode-enclave:11001
            rpctimeout: 10s
        l1:
            websocketurl: "ws://sepolia-l1-node-02.uksouth.cloudapp.azure.com:81?id=tenuserpwd"
            l1beaconurl: "https://ethereum-sepolia-beacon-api.publicnode.com"
            l1blobarchiveurl: "https://eth-beacon-chain-sepolia.drpc.org/rest/"
            rpctimeout: 15s
        log:
            level: 3
            path: sys_out
        p2p:
            isdisabled: false
            bindaddress: 0.0.0.0:10000
            timeout: 10s
        rpc:
            address: 0.0.0.0
            enablehttp: true
            httpport: 80
            enablews: true
            wsport: 81
    enclave:
        simulation: false
        enableattestation: true
        db:
            useinmemory: false
            edgelessdbhost: obscuronode-edgelessdb
            sqlitepath: ""
        debug:
            enabledebugnamespace: true
            enableprofiler: false
        l1:
            enableblockvalidation: false
            genesisjson: []
        log:
            level: 3
            path: sys_out
        rpc:
            bindaddress: 0.0.0.0:11001
            timeout: 5s
externalSecrets:
  enabled: true
  secretMappings:
    NODE_PRIVATEKEY: "UAT-SEQUENCER-NODE-PRIVATEKEY" #Private key of the node