image:
  repository: postgres
  tag: 16-alpine
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
nodeSelector: {}
enclave:
  image:
    tag: 2d27f2e
enclave02:
  image:
    tag: 2d27f2e
host:
  image:
    tag: 2d27f2e
gateway:
  image:
    tag: bbb8af7
