nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

faucet:
  replicaCount: 1
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/faucet_uat_testnet
    tag: latest
  nodeHost: "uat-validator-01.ten.xyz"
  nodePort: "8085"
  pk: "YOUR_FAUCET_PRIVATE_KEY"
  jwtSecret: "YOUR_JWT_SECRET"
  host: "faucet.tenscan.io"

tenscan:
  api:
    replicaCount: 1
    image:
      repository: testnetobscuronet.azurecr.io/obscuronet/api_obscuro_scan_uat_testnet
      tag: latest
    nodeHostAddress: "uat-validator-01.ten.xyz:8085"
    host: "uat-testnet-api.tenscan.io"

  fe:
    replicaCount: 1
    image:
      repository: testnetobscuronet.azurecr.io/obscuronet/fe_obscuro_scan_uat_testnet
      tag: latest
    env:
      apiHost: "https://uat-testnet-api.tenscan.io"
      version: "v1.0.0"
      environment: "uat"
    host: "uat-testnet.tenscan.io"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
