global:
  imagePullSecrets: []
  imagePullPolicy: Always
  destructiveDeployment: true
enclave:
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/enclave
    tag: "8e70989"
  nodeSelector:
    kubernetes.io/hostname: aks-sgxpool-23126921-vmss00002h
  secretEnv:
    ENCLAVE_DB_SQLITEPATH: ""
  edb:
    # image:
    #   repository: "ghcr.io/edgelesssys/edgelessdb-sgx-4gb"
    #   tag: "v0.3.2"
    #   pullPolicy: "Always"
    resources:
      limits:
        memory: 8Gi
        cpu: 4000m
        sgx.intel.com/epc: 6Gi
        sgx.intel.com/provision: 10
        sgx.intel.com/enclave: 10
      requests:
        memory: 6Gi
        cpu: 3000m
        sgx.intel.com/epc: 6Gi
        sgx.intel.com/provision: 10
        sgx.intel.com/enclave: 10
host:
  image:
    repository: "testnetobscuronet.azurecr.io/obscuronet/host"
    tag: "8e70989"
  fqdn: uat-validator-02.ten.xyz
  nodeSelector:
    kubernetes.io/hostname: aks-sgxpool-23126921-vmss00002h
config:
  network:
    chainid: 7443
    genesisjson: '{}'
    batch:
      interval: 1s
      maxinterval: 1s
      maxsize: 56320
    gas:
      basefee: "100000000"
      mingasprice: "100000000"
      paymentaddress: "0xd6C9230053f45F873Cb66D8A02439380a37A4fbF"
      batchexecutionlimit: "300000000"
      localexecutioncap: "300000000000"
    l1:
      chainid: "11155111"
      blocktime: 15s
      starthash: "{{ .Values.l1Config.starthash }}"
      l1contracts:
        messagebus: "{{ .Values.l1Config.messagebus }}"
        bridge: "{{ .Values.l1Config.bridge }}"
        crosschain: "{{ .Values.l1Config.crosschain }}"
        rollup: "{{ .Values.l1Config.rollup }}"
        enclaveRegistry: "{{ .Values.l1Config.enclaveRegistry }}"
        networkConfig: "{{ .Values.l1Config.networkConfig }}"
    rollup:
      interval: 6h
      maxinterval: 10m0s
      maxsize: 131072
    sequencer:
      p2paddress: uat-sequencer-ten-node-host:10000
      systemcontractsupgrader: "0x76d412eBaA22Ab58783531b585128Cf50768abbE"
    crosschain:
      interval: 6s
  node:
    nodetype: "validator"
    name: "ten-uat-validator-02"
    isgenesis: false
    hostAddress: "uat-validator-02.ten.xyz:10000"
  host:
    db:
      useinmemory: false
      sqlitepath: ""
      historicaltxcount: "5107067"
      historicalcontractcount: "947100"
    debug:
      enablemetrics: true
      metricshttpport: 0
      enableprofiler: false
      enabledebugnamespace: true
    enclave:
      rpcaddresses:
        - obscuronode-enclave:11001
      rpctimeout: 10s
    l1:
      websocketurl: "ws://l1.sepolia.ten.xyz:8546"
      l1beaconurl: "http://beacon.sepolia.ten.xyz:5052"
      l1blobarchiveurl: "https://eth-beacon-chain-sepolia.drpc.org/rest/"
      rpctimeout: 15s
    log:
      level: 3
      path: sys_out
    p2p:
      isdisabled: false
      bindaddress: 0.0.0.0:10000
      timeout: 10s
    rpc:
      address: 0.0.0.0
      enablehttp: true
      httpport: 80
      enablews: true
      wsport: 81
  enclave:
    simulation: false
    enableattestation: true
    db:
      useinmemory: false
      edgelessdbhost: obscuronode-edgelessdb
      sqlitepath: ""
    debug:
      enabledebugnamespace: true
      enableprofiler: false
    l1:
      enableblockvalidation: false
      genesisjson: []
    log:
      level: 3
      path: sys_out
    rpc:
      bindaddress: 0.0.0.0:11001
      timeout: 5s
externalSecrets:
  enabled: true
  secretMappings:
    NODE_PRIVATEKEY: "UAT-VALIDATOR-02-NODE-PRIVATEKEY"
    HOST_DB_POSTGRESHOST: "val-02-db-connstring"
enclave02:
  image:
    tag: "8e70989"
gateway:
  image:
    tag: "8e70989"
