global:
  imagePullSecrets: []
  imagePullPolicy: Always
  destructiveDeployment: true

enclave:
  replicaCount: 1
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/enclave
    tag: "v1.5.6"
  nodeSelector:
    kubernetes.io/hostname: aks-sgxpool-23126921-vmss000021
  secretEnv:
    ENCLAVE_DB_SQLITEPATH: ""
  edb:
    # image:
    #   repository: "ghcr.io/edgelesssys/edgelessdb-sgx-4gb"
    #   tag: "v0.3.2"
    #   pullPolicy: "Always"
    resources:
      limits:
        memory: 8Gi
        cpu: 4000m
        sgx.intel.com/epc: 6Gi
        sgx.intel.com/provision: 10
        sgx.intel.com/enclave: 10
      requests:
        memory: 6Gi
        cpu: 2000m
        sgx.intel.com/epc: 6Gi
        sgx.intel.com/provision: 10
        sgx.intel.com/enclave: 10
enclave02:
  enabled: true
  replicaCount: 1
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/enclave
    tag: "v1.5.6"
  nodeSelector:
    kubernetes.io/hostname: aks-sgxpool-23126921-vmss000022
  secretEnv:
    ENCLAVE_DB_SQLITEPATH: ""
  edb:
    # image:
    #   repository: "ghcr.io/edgelesssys/edgelessdb-sgx-4gb"
    #   tag: "v0.3.2"
    #   pullPolicy: "Always"
    resources:
      limits:
        memory: 6Gi
        cpu: 2000m
        sgx.intel.com/epc: 6Gi
        sgx.intel.com/provision: 10
        sgx.intel.com/enclave: 10
      requests:
        memory: 4Gi
        cpu: 2000m
        sgx.intel.com/epc: 6Gi
        sgx.intel.com/provision: 10
        sgx.intel.com/enclave: 10

host:
  image:
    repository: "testnetobscuronet.azurecr.io/obscuronet/host"
    tag: "v1.5.6"
  fqdn: uat-testnet-sequencer.ten.xyz
  nodeSelector:
    kubernetes.io/hostname: aks-sgxpool-23126921-vmss000021

config:
  network:
    chainid: 8443
    genesisjson: '{}'
    batch:
      interval: 1s
      maxinterval: 1s
      maxsize: 56320
    gas:
      basefee: "100000000"
      mingasprice: "100000000"
      paymentaddress: "0xd6C9230053f45F873Cb66D8A02439380a37A4fbF"
      batchexecutionlimit: "300000000"
      localexecutioncap: "300000000000"
    l1:
      chainid: "11155111"
      blocktime: 15s
      starthash: "{{ .Values.l1Config.starthash }}"
      rollupRetryDelay: 10s
      l1contracts:
        messagebus: "{{ .Values.l1Config.messagebus }}"
        bridge: "{{ .Values.l1Config.bridge }}"
        crosschain: "{{ .Values.l1Config.crosschain }}"
        rollup: "{{ .Values.l1Config.rollup }}"
        enclaveRegistry: "{{ .Values.l1Config.enclaveRegistry }}"
        networkConfig: "{{ .Values.l1Config.networkConfig }}"
    rollup:
      interval: 6h
      maxinterval: 10m0s
      maxsize: 131072
    sequencer:
      p2paddress: uat-sequencer.ten.xyz:10000
      systemcontractsupgrader: "0x76d412eBaA22Ab58783531b585128Cf50768abbE"
    crosschain:
      interval: 6s
  node:
    nodetype: "sequencer"
    name: "obscuronode"
    isgenesis: true
    hostAddress: "uat-sequencer.ten.xyz:10000"
  host:
    db:
      useinmemory: false
      sqlitepath: ""
      historicaltxcount: "51070"
      historicalcontractcount: "1076"
    debug:
      enablemetrics: true
      metricshttpport: 0
      enableprofiler: false
      enabledebugnamespace: true
    enclave:
      rpcaddresses:
        - obscuronode-enclave:11001
        - obscuronode-enclave02:11001
      rpctimeout: 10s
    l1:
      websocketurl: "ws://l1.sepolia.ten.xyz:8546"
      l1beaconurl: "http://beacon.sepolia.ten.xyz:5052"
      l1blobarchiveurl: "https://eth-beacon-chain-sepolia.drpc.org/rest/"
      rpctimeout: 15s
    log:
      level: 3
      path: sys_out
    p2p:
      isdisabled: false
      bindaddress: 0.0.0.0:10000
      timeout: 10s
    rpc:
      address: 0.0.0.0
      enablehttp: true
      httpport: 80
      enablews: true
      wsport: 81
  enclave:
    simulation: false
    enableattestation: true
    db:
      useinmemory: false
      edgelessdbhost: obscuronode-edgelessdb
      sqlitepath: ""
    debug:
      enabledebugnamespace: true
      enableprofiler: false
    l1:
      enableblockvalidation: false
      genesisjson: []
    log:
      level: 3
      path: sys_out
    rpc:
      bindaddress: 0.0.0.0:11001
      timeout: 5s

externalSecrets:
  enabled: true
  secretMappings:
    NODE_PRIVATEKEY: "UAT-SEQUENCER-NODE-PRIVATEKEY"
    HOST_DB_POSTGRESHOST: "seq-db-connstring"
