nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
faucet:
  replicaCount: 1
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/faucet_uat_testnet
    tag: latest
  nodeHost: "uat-validator-01.ten.xyz"
  nodePort: "80"
  pk: "YOUR_FAUCET_PRIVATE_KEY"
  jwtSecret: "YOUR_JWT_SECRET"
  chainID: 7443
  host: "uat-faucet.ten.xyz"
tenscan:
  api:
    replicaCount: 1
    image:
      repository: testnetobscuronet.azurecr.io/obscuronet/api_obscuro_scan_uat_testnet
      tag: latest
    nodeHostAddress: "http://uat-validator-01.ten.xyz:80"
    host: "uat-testnet-api.tenscan.io"
  fe:
    replicaCount: 1
    image:
      repository: testnetobscuronet.azurecr.io/obscuronet/fe_obscuro_scan_uat_testnet
      tag: latest
    env:
      apiHost: "https://uat-testnet-api.tenscan.io"
      version: "v1.0.0"
      environment: "uat"
    host: "uat-testnet.tenscan.io"
bridge:
  frontend:
    enabled: true
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
enclave:
  image:
    tag: "0714063"
enclave02:
  image:
    tag: "0714063"
host:
  image:
    tag: "0714063"
gateway:
  image:
    tag: "0714063"
global:
  destructiveDeployment: true
