apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sepolia-ten-tools
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ten-protocol/ten-apps.git
    targetRevision: main
    path: charts/ten-tools
    helm:
      valueFiles:
        - >-
          ../../nonprod-argocd-config/apps/envs/sepolia/valuesFile/values-sepolia-tools.yaml
      parameters:
        - name: faucet.pk
          value: ''
        - name: faucet.jwtSecret
          value: ''
        - name: faucet.defaultAmount
          value: '0.1'
        - name: faucet.nodeHost
          value: sepolia-validator-01.ten.xyz
  destination:
    server: https://kubernetes.default.svc
    namespace: sepolia
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
