apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sepolia-validator-02
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ten-protocol/ten-apps.git
    targetRevision: main
    path: charts/ten-node             # <-- Path to actual chart
    helm:
      valueFiles:
        - ../../nonprod-argocd-config/apps/envs/sepolia/valuesFile/values-sepolia-validator-02.yaml
        - ../../nonprod-argocd-config/apps/envs/sepolia/valuesFile/l1-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sepolia
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
