apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uat-eth-node-mainnet
  namespace: argocd
spec:
  project: default
  # Ignore service type changes (manually set to LoadBalancer for external access)
  ignoreDifferences:
    - group: ""
      kind: Service
      name: uat-eth-node-mainnet-execution
      jsonPointers:
        - /spec/type
        - /spec/ports
    - group: ""
      kind: Service
      name: uat-eth-node-mainnet-beacon
      jsonPointers:
        - /spec/type
        - /spec/ports
  sources:
    - repoURL: https://ethpandaops.github.io/ethereum-helm-charts
      chart: ethereum-node
      targetRevision: 0.2.4
      helm:
        valueFiles:
          - $values/nonprod-argocd-config/apps/envs/uat/valuesFile/values-uat-eth-node-mainnet.yaml
    - repoURL: https://github.com/ten-protocol/ten-apps.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ethereum-mainnet
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
