apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uat-postgres-client
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ten-protocol/ten-apps.git
    targetRevision: main
    path: charts/postgres-client
    helm:
      valueFiles:
        - ../../nonprod-argocd-config/apps/envs/uat/valuesFile/values-uat-postgres-client.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: uat
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
