replicaCount: 1



frontend:
  name: obscuro-gateway
  domain: gw-dev.ten.xyz
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/obscuro_gateway_dev_testnet_fe
    tag: latest
    pullPolicy: Always
  containerPort: 80
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi

backend:
  name: obscuro-gateway
  domain: rpc.gw-dev.ten.xyz
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/obscuro_gateway_dev_testnet
    tag: latest
    pullPolicy: Always
  nodeHost: "dev-validator-01.ten.xyz:10000"
  dbType: "cosmosDB"
  rateLimitUserComputeTime: 0
  rateLimitWindow: "1m"
  maxConcurrentRequestsPerUser: 5
  encryptionKeySource: "new"
  insideEnclave: true
  enableTLS: true
  tlsDomain: "rpc.gw-dev.ten.xyz"
  verbose: false
  nodePortHTTP: 80
  nodePortWS: 443
  ports:
    http: 80
    https: 443
    websocket: 443
    websocket81: 81
  env: 
    OE_SIMULATION: "0"
  dbConnectionURL: "REPLACE_ME"

  pvc:
    enabled: true
    name: ""
    storageClassName: "default"
    accessMode: ReadWriteOnce
    size: 1Gi

  resources: 
    limits:
      cpu: 1
      memory: 2Gi
      sgx.intel.com/epc: 1Gi
      sgx.intel.com/provision: 10
      sgx.intel.com/enclave: 10
    requests:
      cpu: 500m
      memory: 2Gi
      sgx.intel.com/epc: 1Gi
      sgx.intel.com/provision: 10
      sgx.intel.com/enclave: 10
  nodeSelector: {}
  tolerations: []
  affinity: {}

externalSecrets:
  enabled: true
  secretMappings:
    dbConnectionURL: "uattestnet-gateway-connection-string"