replicaCount: 1



frontend:
  name: obscuro-gateway
  domain: gw-dev.ten.xyz
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/obscuro_gateway_dev_testnet_fe
    tag: latest
    pullPolicy: Always
  containerPort: 80
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi

backend:
  name: obscuro-gateway
  domain: rpc.gw-dev.ten.xyz
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/obscuro_gateway_dev_testnet
    tag: latest
    pullPolicy: IfNotPresent
  nodeHost: "dev-validator-01.ten.xyz:10000"
  dbType: "cosmosDB"
  rateLimitUserComputeTime: 0
  rateLimitWindow: "1m"
  maxConcurrentRequestsPerUser: 5
  keyExchangeURL: ""
  insideEnclave: true
  enableTLS: true
  tlsDomain: "rpc.gw-dev.ten.xyz"
  verbose: false
  ports:
    http: 443
    https: 443
    websocket: 443
  env: 
    OE_SIMULATION: "0"
  dbConnectionURL: "REPLACE_ME"

  pvc:
    enabled: true
    name: ""
    storageClassName: "default"
    accessMode: ReadWriteOnce
    size: 1Gi

resources: 
  limits:
    cpu: 1000m
    memory: 5Gi
  requests:
    cpu: 500m
    memory: 5Gi
nodeSelector: {}
tolerations: []
affinity: {}