apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-client
  labels:
    app: postgres-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-client
  template:
    metadata:
      labels:
        app: postgres-client
    spec:
      containers:
      - name: postgres-client
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - sleep
          - infinity
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: PGHOST
          value: ""
        - name: PGPORT
          value: "5432"
        - name: PGUSER
          value: ""
        - name: PGDATABASE
          value: ""
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
