{{- if .Values.global.destructiveDeployment }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ten-node.fullname" . }}-cleanup-sql-script
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ten-node.name" . }}-cleanup-script
    helm.sh/chart: {{ include "ten-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-8"
data:
  cleanup.sql: |-
    DO
    $$
    DECLARE
      db RECORD;
    BEGIN
      FOR db IN
        SELECT datname FROM pg_database WHERE datname LIKE 'host\_%' ESCAPE '\'
      LOOP
        RAISE NOTICE 'Dropping database: %', db.datname;
        EXECUTE format('DROP DATABASE IF EXISTS "%I"', db.datname);
      END LOOP;
    END
    $$;
{{- end }}
