{{- if .Values.edb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ten-node.fullname" . }}-edb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: edgelessdb-sql-api
    app.kubernetes.io/component: api-port
    app.kubernetes.io/part-of: EdgelessDB
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: database
    app.kubernetes.io/name: EdgelessDB
  ports:
  - name: sql
    port: {{ .Values.edb.sqlApiPort }}
    targetPort: {{ .Values.edb.sqlApiPort }}
  - name: http
    port: {{ .Values.edb.restApiPort }}
    targetPort: {{ .Values.edb.restApiPort }}
{{- end }}