apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ten-node.fullname" . }}-enclave
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.enclave.pvc.size }}
  storageClassName: {{ .Values.enclave.pvc.storageClass }}
