apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ten-node.fullname" . }}-enclave-db
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: edgelessdb-storage
    app.kubernetes.io/component: persistent-storage
    app.kubernetes.io/part-of: Enclave
    {{- include "ten-node.labels" . | nindent 4 }}
  annotations:
     argocd.argoproj.io/sync-wave: "1"
spec:
    storageClassName: managed-premium
    {{- toYaml .Values.enclave.edb.storage.spec | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ten-node.fullname" . }}-enclave
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-enclave
    {{- include "ten-node.labels" . | nindent 4 }}
spec:
    storageClassName: {{ .Values.enclave.storage.storageClassName | default "azurefile" }}
    {{- toYaml .Values.enclave.storage.spec | nindent 4 }}
