{{- if .Values.enclave02.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ten-node.fullname" . }}-enclave02
  labels:
    app: {{ .Release.Name }}-enclave02
    {{- include "ten-node.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.enclave02.secretEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}