apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ten-node.fullname" . }}-enclave
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: edgelessdb-storage
    app.kubernetes.io/component: persistent-storage
    app.kubernetes.io/part-of: EdgelessDB
    app.kubernetes.io/part-of: Enclave
    app: {{ .Release.Name }}-enclave
    {{- include "ten-node.labels" . | nindent 4 }}
spec:
    {{- toYaml .Values.enclave.edb.storage.spec | nindent 4 }}
