apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "ten-node.fullname" . }}-tcp
  labels:
    {{- include "ten-node.labels" . | nindent 4 }}
spec:
  entryPoints:
    - p2p
  routes:
    - match: HostSNI(`{{ .Values.host.fqdn }}`)
      services:
        - name: {{ include "ten-node.fullname" . }}-host
          port: 10000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "ten-node.fullname" . }}-http
  labels:
    {{- include "ten-node.labels" . | nindent 4 }}
spec:
  entryPoints:
    - http  # Ensure Traefik is listening on the "http" entry point for port 80
  routes:
    - match: Host(`{{ .Values.host.fqdn }}`)
      kind: Rule
      services:
        - name: {{ include "ten-node.fullname" . }}-host
          port: 80  # The same port exposed in the Service definition