apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "ten-node.fullname" . }}-p2p
  labels:
    {{- include "ten-node.labels" . | nindent 4 }}
spec:
  entryPoints:
    - p2p
  routes:
    - match: HostSNI(`{{ .Values.host.fqdn }}`)
      services:
        - name: {{ include "ten-node.fullname" . }}-host
          port: 10000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "ten-node.fullname" . }}-rpc
  labels:
    {{- include "ten-node.labels" . | nindent 4 }}
spec:
  entryPoints:
    - rpc
  routes:
    - match: HostSNI(`{{ .Values.host.fqdn }}`)
      services:
        - name: {{ include "ten-node.fullname" . }}-host
          port: 8085
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "ten-node.fullname" . }}-ws
  labels:
    {{- include "ten-node.labels" . | nindent 4 }}
spec:
  entryPoints:
    - ws
  routes:
    - match: HostSNI(`{{ .Values.host.fqdn }}`)
      services:
        - name: {{ include "ten-node.fullname" . }}-host
          port: 8089