{{- if .Values.host.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ten-node.fullname" . }}-host
  labels:
    app: {{ .Release.Name }}-host
    {{- include "ten-node.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.host.secretEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
