
{{- if and .Values.global.destructiveDeployment .Values.cleanupJob.pvc.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cleanupJob.pvc.serviceAccount.name | default (printf "%s-pvc-cleaner" (include "ten-node.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ten-node.name" . }}-pvc-cleaner-sa
    helm.sh/chart: {{ include "ten-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10" # Run before the DB cleanup
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.cleanupJob.pvc.serviceAccount.name | default (printf "%s-pvc-cleaner" (include "ten-node.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ten-node.name" . }}-pvc-cleaner-role
    helm.sh/chart: {{ include "ten-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["list", "delete"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["list","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.cleanupJob.pvc.serviceAccount.name | default (printf "%s-pvc-cleaner" (include "ten-node.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ten-node.name" . }}-pvc-cleaner-rb
    helm.sh/chart: {{ include "ten-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
subjects:
- kind: ServiceAccount
  name: {{ .Values.cleanupJob.pvc.serviceAccount.name | default (printf "%s-pvc-cleaner" (include "ten-node.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.cleanupJob.pvc.serviceAccount.name | default (printf "%s-pvc-cleaner" (include "ten-node.fullname" .)) }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}