apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ten-gateway.fullname" . }}-backend-secret
  labels:
    {{- include "ten-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  dbConnectionURL: {{ .Values.backend.dbConnectionURL | b64enc }}
