apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ten-gateway.fullname" . }}-backend-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backend.pvc.size }}
  storageClassName: {{ .Values.backend.pvc.storageClass }}
