apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ten-gateway.fullname" . }}-backend-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: {{ include "ten-gateway.fullname" . }}-backend-secret
    creationPolicy: Owner
  data:
    {{- range $secretKey, $vaultKey := .Values.externalSecrets.secretMappings }}
    - secretKey: {{ $secretKey | quote }}
      remoteRef:
        key: {{ $vaultKey | quote }}
    {{- end }}