nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

faucet:
  replicaCount: 1
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/faucet_dev_testnet
    tag: latest
  nodeHost: "dev-validator-01.ten.xyz"
  nodePort: "80"
  pk: "YOUR_FAUCET_PRIVATE_KEY"
  jwtSecret: "YOUR_JWT_SECRET"
  defaultAmount: 100
  chainID: 443
  host: "dev-faucet.ten.xyz"

tenscan:
  api:
    replicaCount: 0
    image:
      repository: testnetobscuronet.azurecr.io/obscuronet/api_obscuro_scan_dev_testnet
      tag: latest
    nodeHostAddress: "http://dev-validator-01.ten.xyz:80"
    host: "dev-testnet-api.ten.xyz"

  fe:
    replicaCount: 0
    image:
      repository: testnetobscuronet.azurecr.io/obscuronet/fe_obscuro_scan_dev_testnet
      tag: latest
    env:
      apiHost: "https://dev-testnet-api.ten.xyz"
      version: "v1.0.0"
      environment: "dev"
    host: "dev-testnet.ten.xyz"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
