replicaCount: 1

frontend:
  name: obscuro-gateway
  domain: dev-gw-testnet.ten.xyz
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/obscuro_gateway_dev_testnet_fe_k8s
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 80
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi

backend:
  name: obscuro-gateway
  domain: rpc.dev-gw-testnet.ten.xyz
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/obscuro_gateway_dev_testnet_k8s
    tag: latest
    pullPolicy: Always
  nodeHost: "erpc.dev-testnet.ten.xyz"
  dbType: "cosmosDB"
  rateLimitUserComputeTime: 0
  rateLimitWindow: "1m"
  maxConcurrentRequestsPerUser: 5
  encryptionKeySource: "new"
  insideEnclave: true
  enableTLS: true
  tlsDomain: "rpc.dev-gw-testnet.ten.xyz"
  nodePortHTTP: 80
  nodePortWS: 81
  verbose: true
  ports:
    http: 80
    https: 443
    websocket: 443
  env: 
    OE_SIMULATION: "0"
  dbConnectionURL: "REPLACE_ME"

  pvc:
    enabled: true
    name: ""
    storageClassName: "managed"
    accessMode: ReadWriteOnce
    size: 1Gi

  resources: 
    limits:
      cpu: 1
      memory: 5Gi
    requests:
      cpu: 500m
      memory: 5Gi
  nodeSelector:
      kubernetes.io/hostname: aks-sgxpool-23126921-vmss00000t
  tolerations: []
  affinity: {}

externalSecrets:
  enabled: true
  secretMappings:
    dbConnectionURL: "devtestnet-gateway-connection-string"