global:
  imagePullSecrets: []
  imagePullPolicy: Always
  destructiveDeployment: true

enclave:
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/dev_enclave
    tag: "latest"
  nodeSelector:
    kubernetes.io/hostname: aks-sgxpool-23126921-vmss00000x
  secretEnv:
    ENCLAVE_DB_SQLITEPATH: ""
  edb:
    resources:
      limits:
        memory: 8Gi
        cpu: 4000m
        sgx.intel.com/epc: 6Gi
        sgx.intel.com/provision: 10
        sgx.intel.com/enclave: 10
      requests:
        memory: 6Gi
        cpu: 3000m
        sgx.intel.com/epc: 6Gi
        sgx.intel.com/provision: 10
        sgx.intel.com/enclave: 10
  
host:
  image:
    repository: "testnetobscuronet.azurecr.io/obscuronet/dev_host"
    tag: "latest"
  fqdn: dev-validator-01.ten.xyz
  nodeSelector:
    kubernetes.io/hostname: aks-sgxpool-23126921-vmss00000x

config:
  network:
    chainid: 443
    genesisjson: '{}'
    batch:
      interval: 1s
      maxinterval: 1s
      maxsize: 56320
    gas:
      basefee: "100000000"
      mingasprice: "100000000"
      paymentaddress: "0xd6C9230053f45F873Cb66D8A02439380a37A4fbF"
      batchexecutionlimit: "300000000"
      localexecutioncap: "300000000000"
    l1:
      chainid: "1337"
      blocktime: 15s
      starthash: "{{ .Values.l1Config.starthash }}"
      l1contracts:
        messagebus: "{{ .Values.l1Config.messagebus }}"
        bridge: "{{ .Values.l1Config.bridge }}"
        crosschain: "{{ .Values.l1Config.crosschain }}"
        rollup: "{{ .Values.l1Config.rollup }}"
        enclaveRegistry: "{{ .Values.l1Config.enclaveRegistry }}"
        networkConfig: "{{ .Values.l1Config.networkConfig }}"
    rollup:
      interval: 15m0s
      maxinterval: 10m0s
      maxsize: 131072
    sequencer:
      p2paddress: dev-sequencer-ten-node-host:10000
      systemcontractsupgrader: "0x11431A88Fc53F3eE5Ae263067F96EAF91A0f0974"
    crosschain:
      interval: 6s
  node:
    nodetype: "validator"
    name: "ten-dev-validator-01"
    isgenesis: false
    hostAddress: "dev-validator-01.ten.xyz:10000"
  host:
    db:
      useinmemory: false
      sqlitepath: ""
    debug:
      enablemetrics: true
      metricshttpport: 0
      enableprofiler: false
      enabledebugnamespace: true
    enclave:
      rpcaddresses:
        - obscuronode-enclave:11001
      rpctimeout: 10s
    l1:
      websocketurl: "ws://dev-testnet-eth2network-522.uksouth.cloudapp.azure.com:9000"
      l1beaconurl: "dev-testnet-eth2network-522.uksouth.cloudapp.azure.com:12600"
      l1blobarchiveurl: ""
      rpctimeout: 15s
    log:
      level: 3
      path: sys_out
    p2p:
      isdisabled: false
      bindaddress: 0.0.0.0:10000
      timeout: 10s
    rpc:
      address: 0.0.0.0
      enablehttp: true
      httpport: 80
      enablews: true
      wsport: 81
  enclave:
    simulation: false
    enableattestation: true
    db:
      useinmemory: false
      edgelessdbhost: obscuronode-edgelessdb
      sqlitepath: ""
    debug:
      enabledebugnamespace: true
      enableprofiler: false
    l1:
      enableblockvalidation: false
      genesisjson: []
    log:
      level: 3
      path: sys_out
    rpc:
      bindaddress: 0.0.0.0:11001
      timeout: 5s

externalSecrets:
  enabled: true
  secretMappings:
    NODE_PRIVATEKEY: "DEV-VALIDATOR-01-NODE-PRIVATEKEY"
    HOST_DB_POSTGRESHOST: "dev-psql-db-connstring"
