apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ten-dev-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploys after root
spec:
  project: default
  source:
    repoURL: https://github.com/ten-protocol/ten-apps.git
    targetRevision: main
    path: nonprod-argocd-config/apps/envs/dev
    directory:
      recurse: true  # Find all apps in subdirectories
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true