global:
  imagePullSecrets: []
  imagePullPolicy: Always
  destructiveDeployment: false

enclave:
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/enclave
    tag: "v1.5.5"
  nodeSelector:
    kubernetes.io/hostname: aks-sgxpool02-25481487-vmss000003
  secretEnv:
    ENCLAVE_DB_SQLITEPATH: ""
  edb:
    resources:
      limits:
        memory: 8Gi
        cpu: 4000m
        sgx.intel.com/epc: 6Gi
        sgx.intel.com/provision: 10
        sgx.intel.com/enclave: 10
      requests:
        memory: 6Gi
        cpu: 3000m
        sgx.intel.com/epc: 6Gi
        sgx.intel.com/provision: 10
        sgx.intel.com/enclave: 10
    storage:
        spec:
          storageClassName: "premium2-disk-sc"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Ti

host:
  image:
    repository: "testnetobscuronet.azurecr.io/obscuronet/host"
    tag: "v1.5.5"
  fqdn: validator-02.ten.xyz
  nodeSelector:
    kubernetes.io/hostname: aks-sgxpool02-25481487-vmss000003

config:
  network:
    chainid: 443
    genesisjson: '{}'
    batch:
      interval: 1s
      maxinterval: 1s
      maxsize: 56320
    gas:
      basefee: "100000000"
      mingasprice: "100000000"
      paymentaddress: "0x5EE3113aA489A61c5E17cC17f09a10218498b9BC"
      batchexecutionlimit: "300000000"
      localexecutioncap: "300000000000"
    l1:
      chainid: "1"
      blocktime: 12s
      starthash: "{{ .Values.l1Config.starthash }}"
      l1contracts:
        messagebus: "{{ .Values.l1Config.messagebus }}"
        bridge: "{{ .Values.l1Config.bridge }}"
        crosschain: "{{ .Values.l1Config.crosschain }}"
        rollup: "{{ .Values.l1Config.rollup }}"
        enclaveRegistry: "{{ .Values.l1Config.enclaveRegistry }}"
        networkConfig: "{{ .Values.l1Config.networkConfig }}"
    rollup:
      interval: 6h
      maxinterval: 10m0s
      maxsize: 131072
    sequencer:
      p2paddress: mainnet-sequencer-ten-node-host:10000
      systemcontractsupgrader: "0x5EE3113aA489A61c5E17cC17f09a10218498b9BC"
    crosschain:
      interval: 6s
  node:
    nodetype: "validator"
    name: "ten-mainnet-validator-02"
    isgenesis: false
    hostAddress: "validator-02.ten.xyz:10000"
  host:
    db:
      useinmemory: false
      sqlitepath: ""
    debug:
      enablemetrics: true
      metricshttpport: 0
      enableprofiler: false
      enabledebugnamespace: false
    enclave:
      rpcaddresses:
        - obscuronode-enclave:11001
      rpctimeout: 10s
    l1:
      websocketurl: "ws://l1.mainnet.ten.xyz:8546"
      l1beaconurl: "http://beacon.mainnet.ten.xyz:5052"
      l1blobarchiveurl: "https://eth-beacon-chain.drpc.org/rest/"
      rpctimeout: 15s
    log:
      level: 1
      path: sys_out
    p2p:
      isdisabled: false
      bindaddress: 0.0.0.0:10000
      timeout: 10s
    rpc:
      address: 0.0.0.0
      enablehttp: true
      httpport: 80
      enablews: true
      wsport: 81
  enclave:
    simulation: false
    enableattestation: true
    db:
      useinmemory: false
      edgelessdbhost: obscuronode-edgelessdb
      sqlitepath: ""
    debug:
      enabledebugnamespace: false
      enableprofiler: false
    l1:
      enableblockvalidation: true
      genesisjson: []
    log:
      level: 1
      path: sys_out
    rpc:
      bindaddress: 0.0.0.0:11001
      timeout: 5s

externalSecrets:
  enabled: true
  secretMappings:
    NODE_PRIVATEKEY: "MAINNET-VALIDATOR-02-NODE-PRIVATEKEY"
    HOST_DB_POSTGRESHOST: "mainnet-val-02-db-connstring"