replicaCount: 1

frontend:
  name: obscuro-gateway
  domain: gateway.ten.xyz
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/obscuro_gateway_mainnet_testnet_fe_k8s
    tag: latest
    pullPolicy: Always
  containerPort: 80
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi

backend:
  name: obscuro-gateway
  domain: rpc.ten.xyz
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/obscuro_gateway_mainnet_testnet_k8s
    tag: latest
    pullPolicy: Always
  nodeHost: "erpc.ten.xyz"
  dbType: "cosmosDB"
  rateLimitUserComputeTime: 0
  rateLimitWindow: "1m"
  maxConcurrentRequestsPerUser: 5
  encryptionKeySource: "new"
  insideEnclave: true
  enableTLS: true
  tlsDomain: "rpc.ten.xyz"
  nodePortHTTP: 80
  nodePortWS: 81
  tenChainID: 443
  frontendURL: "https://gateway.ten.xyz"
  verbose: true
  ports:
    http: 80
    https: 443
    websocket: 443
  env:
    OE_SIMULATION: "0"
  dbConnectionURL: "REPLACE_ME"

  pvc:
    enabled: true
    name: ""
    storageClassName: "managed"
    accessMode: ReadWriteOnce
    size: 1Gi

  resources:
    limits:
      cpu: 2
      memory: 8Gi
    requests:
      cpu: 1
      memory: 8Gi
  nodeSelector:
      kubernetes.io/hostname: aks-sgxpool02-25481487-vmss000004
  tolerations: []
  affinity: {}

externalSecrets:
  enabled: true
  secretMappings:
    dbConnectionURL: "mainnet-gateway-connection-string"