nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

faucet:
  replicaCount: 1
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/faucet_sepolia_testnet
    tag: latest
  nodeHost: "erpc.testnet.ten.xyz"
  nodePort: "80"
  pk: "YOUR_FAUCET_PRIVATE_KEY"
  jwtSecret: "YOUR_JWT_SECRET"
  host: "sepolia-faucet.ten.xyz"

tenscan:
  api:
    replicaCount: 1
    image:
      repository: testnetobscuronet.azurecr.io/obscuronet/api_obscuro_scan_sepolia_testnet
      tag: latest
    nodeHostAddress: "http://erpc.testnet.ten.xyz:80"
    host: "sepolia-testnet-api.tenscan.io"

  fe:
    replicaCount: 1
    image:
      repository: testnetobscuronet.azurecr.io/obscuronet/fe_obscuro_scan_sepolia_testnet
      tag: latest
    env:
      apiHost: "https://sepolia-testnet-api.tenscan.io"
      version: "v1.0.0"
      environment: "sepolia"
    host: "sepolia.tenscan.io"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
