nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

faucet:
  replicaCount: 1
  image:
    repository: testnetobscuronet.azurecr.io/obscuronet/faucet_uat_testnet
    tag: latest
  nodeHost: "l2-validator"
  nodePort: "80"
  pk: "YOUR_FAUCET_PRIVATE_KEY"
  jwtSecret: "YOUR_JWT_SECRET"
  defaultAmount: 0.25
  host: "faucet.tenscan.io"

tenscan:
  api:
    replicaCount: 1
    image:
      repository: testnetobscuronet.azurecr.io/obscuronet/dev_testnet_obscuroscan
      tag: latest
    nodeHostAddress: "l2-validator"
    host: "api.tenscan.io"

  fe:
    replicaCount: 1
    image:
      repository: testnetobscuronet.azurecr.io/obscuronet/dev_testnet_obscuroscan
      tag: latest
    env:
      apiHost: "https://api.tenscan.io"
      version: "v1.0.0"
      environment: "uat"
    host: "tenscan.io"

bridge:
  frontend:
    enabled: false
    replicaCount: 1
    image:
      repository: "testnetobscuronet.azurecr.io/obscuronet/fe_bridge_uat_testnet"
      tag: "latest"
      pullPolicy: Always
    command: ["pnpm", "run", "start-prod"]
    containerPort: 80
    service:
      port: 80
    host: "uat-bridge.ten.xyz"
    env:
      apiHost: "https://rpc.uat-gw-testnet.ten.xyz/v1"
    # You can add other environment variables here
    extraEnv: []
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 1Gi

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
